export enum ENV {
    KEYCLOAK_DOMAIN = 'KEYCLOAK_DOMAIN',
    KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
    KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',
    KEYCLOAK_REALM = 'KEYCLOAK_REALM',
}